# Generated by Django 5.0.7 on 2024-07-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='watermeter',
            options={'verbose_name': 'Счетчик', 'verbose_name_plural': 'Счетчики'},
        ),
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.RemoveField(
            model_name='watermeter',
            name='readings',
        ),
        migrations.AddField(
            model_name='house',
            name='house_number',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='street_name',
            field=models.CharField(default='unknown', max_length=255, verbose_name='Название улицы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.IntegerField(verbose_name='Площадь квартиры'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_unit',
            field=models.FloatField(verbose_name='Цена за услугу'),
        ),
        migrations.CreateModel(
            name='CalculationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField()),
                ('payment_number', models.IntegerField()),
                ('completed_apartments', models.IntegerField(default=0)),
                ('total_apartments', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('house_id', 'payment_number')},
            },
        ),
        migrations.CreateModel(
            name='WaterMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.IntegerField(verbose_name='Показание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='main.watermeter')),
            ],
            options={
                'verbose_name': 'Показание счетчика',
                'verbose_name_plural': 'Показания счетчиков',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField(default=1, verbose_name='Номер платежа')),
                ('water_supply_charge', models.FloatField(verbose_name='Плата за водоснабжение')),
                ('common_property_charge', models.FloatField(verbose_name='Плата за содержание общего имущества')),
                ('total_charge', models.FloatField(verbose_name='Общая квартплата')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartment')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'unique_together': {('apartment', 'payment_number')},
            },
        ),
    ]
